# Generated by Django 5.0.4 on 2024-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('technology', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
