# Generated by Django 5.0.4 on 2024-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0002_myservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myservices',
            name='icon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
