# Generated by Django 5.0.4 on 2024-05-31 21:47

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0003_alter_myservices_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_link', models.CharField(blank=True, default='#', max_length=100)),
                ('bg_img', models.ImageField(upload_to=pathlib.PurePosixPath('/Volumes/Disk1/Projects/Django/portfolio/static/frontwebapp/images'))),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pathlib.PurePosixPath('/Volumes/Disk1/Projects/Django/portfolio/static/frontwebapp/images'))),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='frontwebapp.internships')),
            ],
        ),
    ]
