# Generated by Django 5.0.4 on 2024-05-31 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0004_internships_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='internship',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='frontwebapp.internships'),
        ),
        migrations.AlterField(
            model_name='internships',
            name='bg_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
