# Generated by Django 5.0.4 on 2024-05-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0005_alter_image_image_alter_image_internship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='internship',
        ),
        migrations.AddField(
            model_name='internships',
            name='images',
            field=models.ManyToManyField(blank=True, to='frontwebapp.image'),
        ),
    ]
