# Generated by Django 5.0.4 on 2024-05-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0006_remove_image_internship_internships_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='webpsite_imgs/'),
        ),
        migrations.AlterField(
            model_name='internships',
            name='bg_img',
            field=models.ImageField(upload_to='internship_imgs/'),
        ),
    ]
