# Generated by Django 5.0.4 on 2024-05-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0007_alter_image_image_alter_internships_bg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='internships_imgs/'),
        ),
        migrations.AlterField(
            model_name='internships',
            name='bg_img',
            field=models.ImageField(upload_to='internships_imgs/'),
        ),
    ]
