# Generated by Django 5.0.4 on 2024-06-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0011_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
