# Generated by Django 5.0.4 on 2024-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0012_alter_education_description_alter_education_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='web_link',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
