# Generated by Django 5.0.4 on 2024-06-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontwebapp', '0013_alter_internships_web_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='int_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
